[build]
  publish = "."

[[redirects]]
  from = "http://salonlotus.rs/*"
  to   = "https://salonlotus.rs/:splat"
  status = 301

[[redirects]]
  from = "https://www.salonlotus.rs/*"
  to   = "https://salonlotus.rs/:splat"
  status = 301

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

